---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
  namespace: flux-system
spec:
  chart:
    spec:
      chart: forgejo
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: forgejo
      version: 0.0.x
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: forgejo
  values:
    gitea:
      admin:
        existingSecret: gitea-admin-secret
      config:
        APP_NAME: git.macks.cloud
        service:
          DISABLE_REGISTRATION: true
        database:
          DB_TYPE: postgres
        indexer:
          ISSUE_INDEXER_TYPE: bleve
          REPO_INDEXER_ENABLED: true

    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: git.macks.cloud
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - git.macks.cloud
          secretName: forgejo-tls

    postgresql:
      enabled: true
    postgresql-ha:
      enabled: false
    redis-cluster:
      enabled: false
    redis:
      enabled: true

    persistence:
      enabled: true
