---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
  namespace: flux-system
spec:
  chart:
    spec:
      chart: forgejo
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: forgejo
      version: 0.0.x
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: forgejo
  values:
    gitea:
      config:
        APP_NAME: git.macks.cloud
        database:
          DB_TYPE: postgres
        indexer:
          ISSUE_INDEXER_TYPE: bleve
          REPO_INDEXER_ENABLED: true

    postgresql:
      enabled: true
    postgresql-ha:
      enabled: false
    redis-cluster:
      enabled: false
    redis:
      enabled: true

    persistence:
      enabled: true
