apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-config-pvc
  namespace: freshrss
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
