---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: flux-system
spec:
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn
      version: 1.7.x
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: longhorn
  values:
    defaultSettings:
      replicaSoftAntiAffinity: true
    persistence:
      defaultClassReplicaCount: 1
