apiVersion: v1
kind: Service
metadata:
  name: wakapi
  namespace: wakapi
spec:
  selector:
    app: wakapi
  type: ClusterIP
  ports:
  - name: wakapi
    protocol: TCP
    port: 3000
    targetPort: 3000
