apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wakapi-data-pvc
  namespace: wakapi
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
