---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: flux-system
spec:
  chart:
    spec:
      chart: immich
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: immich
      version: 0.7.x
  install:
    createNamespace: false
  interval: 1m0s
  targetNamespace: immich
  values:
    immich:
      persistence:
        library:
          existingClaim: immich-pvc
    postgresql:
      enabled: true
    redis:
      enabled: true
    server:
      ingress:
        main:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
          hosts:
            - host: immich.macks.cloud
              paths:
                - path: /
          tls:
            - hosts:
              - immich.macks.cloud
              secretName: immich-tls
