apiVersion: v1
kind: Secret
metadata:
    name: picoshare-secret
    namespace: picoshare
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:ReyWXnIIf/ZyNvkyZe/yzraCEfE=,iv:p/V4i/4IARoNcT2tEEebrAvKW5MHPcAnOhgMrcHd6m4=,tag:765ImHWCafoFRmAfa1Xcvw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ytk4e44zdvh8e5ylnr4qcg5zmfg0k2t6a2q5xfa7qgnvq6lt6vjq65nqmh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1dFFGZzN5ckdYWHhpeGlt
            bHFBSXJRMStkMU5KV2ZsZ2hWelQwNVVpWG5rCitHb3ZDME5zR3pTQUJlK0grNTZa
            bk50WmNKcnVRQ1NLeUZIaEZLa2hqZzQKLS0tICt3clRNKzZoTUtaYU1VdS9vMlN2
            bjdKamZIRkZhMy9MWGFMbjB5Um1aVmcKhapvulzMNTeccZrk8yUha31lW/5p3zEF
            VMMbQKfLlHP/HXJo7NqpPi/+5gYEXnk2hZwyYL3M4t3o1nbZSeOzng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-21T20:19:02Z"
    mac: ENC[AES256_GCM,data:Nnd/1/poBSN5rFSlCjDtqPXm1di1C5yw0abTWMMzTsMj4+us9wy+eqQHGm5AKl5nOqHQBK7UUiBhG+1fXopAUrIz8bwWZAbsd3bqpoTd9p3AbGyCOzB3NPoKMlqyHl6f1q/0oS7fFPEjlXpxNMK2N4f1DyY7m1mv75wcupn/IKs=,iv:QbWPKO0epjPsZaHLcJ8dv9w59KpVABO0z3IcX/9gEdg=,tag:fRU4r8miPWl0TzKP5e1xUw==,type:str]
    pgp: []
    encrypted_regex: (^data|stringData)$
    version: 3.9.3
