apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: picoshare-data-pvc
  namespace: picoshare
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
