apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teamspeak-data-pvc
  namespace: teamspeak
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
