apiVersion: v1
kind: Service
metadata:
  name: teamspeak-svc
  namespace: teamspeak
spec:
  selector:
    app: teamspeak
  ports:
    - name: teamspeak-udp
      protocol: UDP
      port: 9987
      targetPort: 9987
    - name: teamspeak-tcp-1
      protocol: TCP
      port: 10011
      targetPort: 10011
    - name: teamspeak-tcp-2
      protocol: TCP
      port: 30033
      targetPort: 30033
  type: LoadBalancer
