apiVersion: apps/v1
kind: Deployment
metadata:
  name: teamspeak
  namespace: teamspeak
  labels:
    app: teamspeak
spec:
  selector:
    matchLabels:
      app: teamspeak
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container:  teamspeak
      labels:
        app: teamspeak
    spec:
      containers:
      - name: teamspeak
        image: teamspeak:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: TS3SERVER_DB_PLUGIN
          value: "ts3db_sqlite3"
        - name: TS3SERVER_DB_SQLCREATEPATH
          value: "create_sqlite3"
        - name: TS3SERVER_LICENSE
          value: "accept"
        ports:
        - containerPort: 9987
          name: teamspeak-udp
          protocol: UDP
        - containerPort: 10011
          name: teamspeak-tcp-1
          protocol: TCP
        - containerPort: 30033
          name: teamspeak-tcp-2
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: teamspeak-data-pvc
      restartPolicy: Always
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
