---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-smb
  namespace: flux-system
spec:
  chart:
    spec:
      chart: csi-driver-smb
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: csi-driver-smb
      version: 1.17.x
  interval: 1m0s
  targetNamespace: kube-system
